# Logging configuration
log:
  level: INFO

accessLog:
  filePath: "/var/log/traefik/access.log" # Path to access log file
  format: common

# Enable the Traefik dashboard and API
api:
  dashboard: true
  insecure: true # Allows access to the dashboard without authentication (not recommended for production)

# Define entry points for HTTP and HTTPS
entryPoints:
  web:
    address: ":80"

    # Enables HTTPS
    # websecure:
    # address: ":443"


# Configure providers (where Traefik gets routing info)
providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true # Auto-reload when files change